# Generated by Django 5.0.6 on 2024-06-06 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("comments", "0001_initial"),
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="blog_page",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="home.blogpage"
            ),
        ),
    ]
